### PR TITLE
Added validate flag to necessary files

### PR DESCRIPTION
**Pull request by LeoKHoward**
# Motivation and Context
Some of the "release" deployments config are missing the validate flag required for Hibernate

# What has changed
Added in flag 

# How to test?
Deploy it

# Links
https://trello.com/c/OLhoOAHB/826-add-hibernate-validate-flag-to-all-release-deployments-2

### CODE REVIEW

**Comment by LeoKHoward** [comment]
[add hibernate validate flag to all "release" deployments (2)](https://trello.com/c/OLhoOAHB/826-add-hibernate-validate-flag-to-all-release-deployments-2)

**Review by AdamHawtin — CHANGES_REQUESTED** [review]
The test config needs to be set to update now. Also we probably want to override it to update in the non-release kubernetes YAML if the default is validate.

**Comment by NickGrantX** [comment]
> The test config needs to be set to update now. Also we probably want to override it to update in the non-release kubernetes YAML if the default is validate.

I'm not so sure I agree with @AdamHawtin - we want the DB to be created using the scripts, not Hibernate, don't we?

**Review by NickGrantX — CHANGES_REQUESTED** [review]
Change is good, but you need to add this override into `application-test.yml`:

```
spring:
  jpa:
    hibernate:
      ddl-auto: update
```

**Review by NickGrantX — APPROVED** [review]
Marvellous 👍

**Comment by AdamHawtin** [comment]
> > The test config needs to be set to update now. Also we probably want to override it to update in the non-release kubernetes YAML if the default is validate.
> 
> I'm not so sure I agree with @AdamHawtin - we want the DB to be created using the scripts, not Hibernate, don't we?

We want it to be but at the moment it isn't and we're relying on hibernate auto update.

**Review by AdamHawtin — APPROVED** [review]

**Comment by AdamHawtin** [comment]
Approving it since we're expecting action scheduler to be updating the DDL in the dev environments

**Pull request merged**
